### ISSUE TITLE
tls_validation: false is ignored

### ISSUE THREAD

**Issue by maciej-markowski** [pulp/pulp_container#1305]
**Version**
```
- component: core
  domain_compatible: true
  package: pulpcore
  version: 3.27.1
- component: ansible
  domain_compatible: false
  package: pulp-ansible
  version: 0.18.0
- component: certguard
  domain_compatible: true
  package: pulp-certguard
  version: 1.6.5
- component: container
  domain_compatible: false
  package: pulp-container
  version: 2.15.0
- component: deb
  domain_compatible: false
  package: pulp_deb
  version: 2.21.0
- component: file
  domain_compatible: true
  package: pulp-file
  version: 1.14.3
- component: maven
  domain_compatible: false
  package: pulp-maven
  version: 0.6.0
- component: ostree
  domain_compatible: false
  package: pulp-ostree
  version: 2.1.0
- component: python
  domain_compatible: false
  package: pulp-python
  version: 3.10.0
- component: rpm
  domain_compatible: true
  package: pulp-rpm
  version: 3.22.0
```

**Describe the bug**
This is in environment with corporate proxy injecting certificate. Despite container remote having `tls_validation` set to false, sync operation fails with
```
'Cannot connect to host ghcr.io:443 ssl:True [SSLCertVerificationError:
    (1, ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed
    certificate in certificate chain (_ssl.c:1131)'')]'
```

**To Reproduce**
Create repository and remote with `tls_validation` disabled.

```
[vagrant@hostname ~]$ pulp container remote show --name remote-multus
ca_cert: null
client_cert: null
connect_timeout: null
download_concurrency: null
exclude_tags: null
headers: null
hidden_fields:
- is_set: false
  name: client_key
- is_set: false
  name: proxy_username
- is_set: false
  name: proxy_password
- is_set: false
  name: username
- is_set: false
  name: password
include_tags:
- v3.8
max_retries: null
name: remote-multus
policy: immediate
proxy_url: null
pulp_created: '2023-06-13T16:32:36.602514Z'
pulp_href: /pulp/api/v3/remotes/container/container/0188b59a-1ef8-7b8a-9cc2-9a774f71a5d8/
pulp_labels: {}
pulp_last_updated: '2023-06-13T16:32:36.602558Z'
rate_limit: null
sigstore: null
sock_connect_timeout: null
sock_read_timeout: null
tls_validation: false
total_timeout: null
upstream_name: k8snetworkplumbingwg/multus-cni
url: https://ghcr.io
```
Run sync task:

```
[vagrant@hostname~]$ pulp container repository sync --name multus --remote remote-multus
Started background task /pulp/api/v3/tasks/0188ba23-ab26-70c6-b681-b738f7ce8472/
...Error: Task /pulp/api/v3/tasks/0188ba23-ab26-70c6-b681-b738f7ce8472/ failed: 'Cannot connect to host ghcr.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')]'
[vagrant@nmdws ~]$ pulp task show --href /pulp/api/v3/tasks/0188ba23-ab26-70c6-b681-b738f7ce8472/
child_tasks: []
created_by: /pulp/api/v3/users/1/
created_resources: []
error:
  description: 'Cannot connect to host ghcr.io:443 ssl:True [SSLCertVerificationError:
    (1, ''[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed
    certificate in certificate chain (_ssl.c:1131)'')]'
  traceback: "  File \"/usr/local/lib/python3.8/site-packages/pulpcore/tasking/tasks.py\"\
    , line 66, in _execute_task\n    result = func(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/pulp_container/app/tasks/synchronize.py\"\
    , line 41, in synchronize\n    return dv.create()\n  File \"/usr/local/lib/python3.8/site-packages/pulpcore/plugin/stages/declarative_version.py\"\
    , line 161, in create\n    loop.run_until_complete(pipeline)\n  File \"/usr/lib64/python3.8/asyncio/base_events.py\"\
    , line 616, in run_until_complete\n    return future.result()\n  File \"/usr/local/lib/python3.8/site-packages/pulpcore/plugin/stages/api.py\"\
    , line 220, in create_pipeline\n    await asyncio.gather(*futures)\n  File \"\
    /usr/local/lib/python3.8/site-packages/pulpcore/plugin/stages/api.py\", line 41,\
    \ in __call__\n    await self.run()\n  File \"/usr/local/lib/python3.8/site-packages/pulp_container/app/tasks/sync_stages.py\"\
    , line 136, in run\n    signature_source = await self.get_signature_source()\n\
    \  File \"/usr/local/lib/python3.8/site-packages/pulp_container/app/tasks/sync_stages.py\"\
    , line 277, in get_signature_source\n    result = await extension_check_downloader.run()\n\
    \  File \"/usr/local/lib/python3.8/site-packages/pulpcore/download/http.py\",\
    \ line 273, in run\n    return await download_wrapper()\n  File \"/usr/local/lib/python3.8/site-packages/backoff/_async.py\"\
    , line 151, in retry\n    ret = await target(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/pulpcore/download/http.py\"\
    , line 258, in download_wrapper\n    return await self._run(extra_data=extra_data)\n\
    \  File \"/usr/local/lib/python3.8/site-packages/pulpcore/download/http.py\",\
    \ line 291, in _run\n    async with self.session.get(\n  File \"/usr/local/lib64/python3.8/site-packages/aiohttp/client.py\"\
    , line 1141, in __aenter__\n    self._resp = await self._coro\n  File \"/usr/local/lib64/python3.8/site-packages/aiohttp/client.py\"\
    , line 536, in _request\n    conn = await self._connector.connect(\n  File \"\
    /usr/local/lib64/python3.8/site-packages/aiohttp/connector.py\", line 540, in\
    \ connect\n    proto = await self._create_connection(req, traces, timeout)\n \
    \ File \"/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py\", line\
    \ 901, in _create_connection\n    _, proto = await self._create_direct_connection(req,\
    \ traces, timeout)\n  File \"/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py\"\
    , line 1206, in _create_direct_connection\n    raise last_exc\n  File \"/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py\"\
    , line 1175, in _create_direct_connection\n    transp, proto = await self._wrap_create_connection(\n\
    \  File \"/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py\", line\
    \ 982, in _wrap_create_connection\n    raise ClientConnectorCertificateError(req.connection_key,\
    \ exc) from exc\n"
finished_at: '2023-06-14T13:41:23.567263Z'
logging_cid: 6123ba207f3b40589c7c02d37e7c2739
name: pulp_container.app.tasks.synchronize.synchronize
parent_task: null
progress_reports:
- code: sync.downloading.artifacts
  done: 0
  message: Downloading Artifacts
  state: canceled
  suffix: null
  total: null
- code: associating.content
  done: 0
  message: Associating Content
  state: canceled
  suffix: null
  total: null
pulp_created: '2023-06-14T13:41:19.782672Z'
pulp_href: /pulp/api/v3/tasks/0188ba23-ab26-70c6-b681-b738f7ce8472/
reserved_resources_record:
- /pulp/api/v3/repositories/container/container/0188b59f-9c89-7148-a8a2-0b896af83f5a/
- shared:/pulp/api/v3/remotes/container/container/0188b59a-1ef8-7b8a-9cc2-9a774f71a5d8/
started_at: '2023-06-14T13:41:19.843529Z'
state: failed
task_group: null
worker: /pulp/api/v3/workers/0188ba1b-8a35-799f-8b39-bf5c97844cdb/
```

**Expected behavior**
Selfsigned certificate (and any other) is not checked during sync, sync completes successfully.
